version: "2"
services:
  mariadb:
    image: mariadb:5.5
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=DB
    ports:
      - "3306:3306"
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mariadb
  php-apache:
    image: php:5.5-apache
    volumes:
      - ./src:/var/www/html
      - /config/php.ini:/usr/local/etc/php/
    working_dir: /var/www/html
    ports:
      - "8000:80"
    links:
      - mariadb
  

###
# docker-compose rm -f
# docker-compose pull
# docker-compose up -d
# docker-compose stop -t 1
###
