mongo:
  image: mongo:2.6.11
  ports:
    - "27017:27017"
application:
  build: .
  command: node --debug=5858 app.js --color=always
  ports:
    - "3000:3000"
    - "5858:5858"
  volumes:
    - .:/app
    - /app/node_modules
  working_dir: /app
  links:
    - mongo

###
# docker-compose rm -f
# docker-compose pull
# docker-compose up --build -d
# docker-compose stop -t 1
###
